server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: inventory_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
