server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
